DROP TABLE equipo;
CREATE TABLE equipo (
  CODIGO varchar2(4) NOT NULL,
  NOMBRE varchar2(30) NOT NULL,
  CONSTRAINT PK_EQUIPO 
	PRIMARY KEY (CODIGO)
);

DROP TABLE jugador;
CREATE TABLE jugador (
  NUMERO NUMERIC(4,0) NOT NULL,
  CODIGO_EQUIPO varchar2(4) NOT NULL,
  NOMBRE varchar2(40) NOT NULL,
  NACIMIENTO date NOT NULL,
  PRIMARY KEY (NUMERO,CODIGO_EQUIPO),
  CONSTRAINT FK_CODIGO_EQUIPO
    FOREIGN KEY (CODIGO_EQUIPO)
    REFERENCES equipo(CODIGO)
);
select * from jugador;
select * from equipo;